"use client";

import { useCallback, useEffect, useState } from "react";
import { configureOfflinePin, getOfflineDevice, getOfflineSnapshot, hasOfflinePin, installationId, listOfflineCommands, pendingOfflineCount, removeOfflineCommands, saveOfflineDevice, saveOfflineSnapshot, unlockOffline, warmOfflineShell } from "./offline-store";

type Props = { pointOfSaleId: string; cashSessionId: string; role: string };
type DeviceRow = { id: string; name: string; status: "ACTIVE" | "SUSPENDED" | "REVOKED"; lastSeenAt: string; lastSynchronizedAt: string | null; pointOfSale: { name: string; store: { name: string } }; _count: { snapshots: number; commands: number } };
async function offlineApi(path: string, method = "GET", body?: unknown) { const response = await fetch(`/api/portal/cash/offline/${path}`, { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json().catch(() => ({})) as { message?: string; [key: string]: unknown }; if (!response.ok) throw new Error(payload.message ?? "Falha na operação offline."); return payload; }

export function OfflineSyncCenter({ pointOfSaleId, cashSessionId, role }: Props) {
  const canManage = ["OWNER", "ADMIN", "MANAGER"].includes(role);
  const [online, setOnline] = useState(true); const [pending, setPending] = useState(0); const [prepared, setPrepared] = useState(false); const [unlocked, setUnlocked] = useState(false); const [expiresAt, setExpiresAt] = useState<string | null>(null); const [pin, setPin] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [devices, setDevices] = useState<DeviceRow[]>([]); const [showDevices, setShowDevices] = useState(false);
  const refresh = useCallback(async () => { setOnline(navigator.onLine); setPending(await pendingOfflineCount()); setPrepared(await hasOfflinePin()); try { setExpiresAt((await getOfflineSnapshot())?.payload.expiresAt ?? null); setUnlocked(true); } catch { setExpiresAt(null); } }, []);
  const loadDevices = useCallback(async () => { if (!canManage || !navigator.onLine) return; setDevices(await offlineApi("dispositivos") as unknown as DeviceRow[]); }, [canManage]);
  useEffect(() => { void refresh(); const update = () => void refresh(); window.addEventListener("online", update); window.addEventListener("offline", update); window.addEventListener("nexus-offline-change", update); return () => { window.removeEventListener("online", update); window.removeEventListener("offline", update); window.removeEventListener("nexus-offline-change", update); }; }, [refresh]);

  async function prepare() { if (!pointOfSaleId || !cashSessionId) return; setBusy(true); setError(""); try { if (!/^\d{6}$/.test(pin)) throw new Error("Informe um PIN local de 6 números para proteger este caixa."); const localInstallationId = await installationId(); const registered = await offlineApi("dispositivos", "POST", { pdv_id: pointOfSaleId, instalacao_id: localInstallationId, nome: `Caixa ${pointOfSaleId.slice(0, 8)}` }) as { device: { id: string; pointOfSaleId: string; name: string } }; await configureOfflinePin(pin); await saveOfflineDevice({ id: registered.device.id, installationId: localInstallationId, pointOfSaleId: registered.device.pointOfSaleId, name: registered.device.name }); await updateSnapshot(registered.device.id); await refresh(); setUnlocked(true); setPin(""); setMessage("Caixa offline protegido e aplicativo local preparado. Guarde o PIN com segurança."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao preparar o caixa."); } finally { setBusy(false); } }
  async function updateSnapshot(deviceId?: string) { const device = deviceId ? { id: deviceId } : await getOfflineDevice(); if (!device) throw new Error("Dispositivo offline não registrado."); const created = await offlineApi("snapshots", "POST", { pdv_id: pointOfSaleId, dispositivo_id: device.id }) as { snapshot: { id: string }; payload: Parameters<typeof saveOfflineSnapshot>[0]["payload"] }; await saveOfflineSnapshot({ id: created.snapshot.id, payload: created.payload }); await warmOfflineShell(); await refresh(); setMessage("Snapshot offline atualizado com preços, saldos e regras vigentes."); }
  async function unlock() { setBusy(true); setError(""); try { await unlockOffline(pin); await refresh(); setPin(""); setMessage("Dados locais desbloqueados neste navegador."); } catch (cause) { setError(cause instanceof Error ? cause.message : "PIN incorreto."); } finally { setBusy(false); } }
  async function synchronize() { setBusy(true); setError(""); try { const commands = await listOfflineCommands(); if (!commands.length) { setMessage("Nenhuma venda offline pendente."); return; } const device = await getOfflineDevice(); if (!device) throw new Error("Dispositivo offline não registrado."); const grouped = new Map<string, typeof commands>(); commands.forEach((command) => grouped.set(command.snapshotId, [...(grouped.get(command.snapshotId) ?? []), command])); const applied: string[] = []; const conflicts: string[] = []; for (const [snapshotId, entries] of grouped) { const result = await offlineApi("sincronizar", "POST", { dispositivo_id: device.id, snapshot_id: snapshotId, comandos: entries.map((entry) => ({ id: entry.id, ocorrido_em: entry.occurredAt, tipo: entry.type, payload: entry.payload })) }) as { results: Array<{ id: string; status: string; error?: string }> }; result.results.forEach((entry) => { if (entry.status === "APPLIED") applied.push(entry.id); else conflicts.push(`${entry.id.slice(0, 8)}: ${entry.error ?? entry.status}`); }); } if (applied.length) await removeOfflineCommands(applied); await refresh(); if (conflicts.length) setError(`Há conflitos que não foram aplicados: ${conflicts.join("; ")}`); else setMessage(`${applied.length} venda(s) sincronizada(s) e revalidada(s).`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha na sincronização."); } finally { setBusy(false); } }
  async function changeDevice(device: DeviceRow, status: DeviceRow["status"]) { const reason = status === "ACTIVE" ? "Reativação administrativa confirmada" : "Bloqueio administrativo do dispositivo"; await offlineApi(`dispositivos/${device.id}`, "PUT", { status, motivo: reason }); await loadDevices(); setMessage(`Dispositivo ${status === "ACTIVE" ? "reativado" : status === "SUSPENDED" ? "suspenso" : "revogado"}.`); }

  return <><section className={`offline-sync ${online ? "online" : "offline"}`}><div><span>{online ? "● ONLINE" : "● OFFLINE"}</span><strong>Sincronização do caixa</strong><small>{expiresAt ? `Snapshot válido até ${new Date(expiresAt).toLocaleString("pt-BR")}` : prepared ? "Informe o PIN para desbloquear os dados locais." : "Prepare o caixa com um PIN local."}</small></div><div className="offline-sync-count"><small>Fila criptografada</small><strong>{pending}</strong></div>{!unlocked && <label className="offline-pin">PIN local<input aria-label="PIN offline" inputMode="numeric" maxLength={6} onChange={(event) => setPin(event.target.value.replace(/\D/g, ""))} placeholder="••••••" type="password" value={pin}/></label>}<button disabled={busy || (!unlocked && pin.length !== 6) || (unlocked && !online)} onClick={unlocked ? () => updateSnapshot() : prepared ? unlock : prepare} type="button">{busy ? "Processando…" : unlocked ? "Atualizar offline" : prepared ? "Desbloquear" : "Preparar offline"}</button><button disabled={!online || !unlocked || busy || pending === 0} onClick={synchronize} type="button">Sincronizar</button><a href="/caixa-offline">Abrir app offline</a>{canManage && <button className="secondary" disabled={!online || busy} onClick={async () => { setShowDevices(!showDevices); if (!showDevices) await loadDevices(); }} type="button">Dispositivos</button>}{message && <p>{message}</p>}{error && <p className="error">{error}</p>}</section>{showDevices && <section className="offline-devices"><header><div><span>GESTÃO DE DISPOSITIVOS</span><strong>Caixas autorizados</strong></div><button onClick={() => setShowDevices(false)}>Fechar</button></header>{devices.map((device) => <article key={device.id}><div><strong>{device.name}</strong><small>{device.pointOfSale.store.name} · {device.pointOfSale.name}</small></div><span className={`status-pill ${device.status.toLowerCase()}`}>{device.status}</span><small>Última sincronização {device.lastSynchronizedAt ? new Date(device.lastSynchronizedAt).toLocaleString("pt-BR") : "nunca"}</small><div>{device.status !== "ACTIVE" && <button onClick={() => changeDevice(device, "ACTIVE")}>Reativar</button>}{device.status === "ACTIVE" && <button onClick={() => changeDevice(device, "SUSPENDED")}>Suspender</button>}{device.status !== "REVOKED" && <button className="danger" onClick={() => changeDevice(device, "REVOKED")}>Revogar</button>}</div></article>)}</section>}</>;
}
