export type Numeric = number | string;
export type TaxRegime = "SIMPLES_NACIONAL" | "LUCRO_PRESUMIDO" | "LUCRO_REAL";
export type FiscalRule = { regime: TaxRegime; cfop: string; cstIcms: string; csosn: string | null; icmsRate: Numeric; mvaRate: Numeric; cstPisCofins: string; revenueNature: string | null; pisRate: Numeric; cofinsRate: Numeric; cstIbsCbs: string; cClassTrib: string; cbsRate: Numeric; ibsRate: Numeric; cbsReduction: Numeric; ibsReduction: Numeric; offsetCbsPisCofins: boolean; metadata: unknown };
export type FiscalCategory = { id: string; code: string; name: string; description: string; ncm: string; cest: string | null; classification: string; ruleVersion: string; validFrom: string; validUntil: string | null; status: string; sourceReferences: Array<{ title?: string; url?: string }>; active: boolean; rules: FiscalRule[]; _count: { products: number } };
export type RegistrationCatalogs = { regimes: TaxRegime[]; classificacoes: string[]; cst_pis_cofins: string[]; cst_icms: string[]; csosn: string[]; naturezas_receita: Array<{ codigo: string; csts: string[]; prefixos_ncm: string[] }>; cclass_trib: Array<{ codigo: string; cst: string; prefixos_ncm: string[]; aliquota_cbs: number; aliquota_ibs: number; reducao: number; exige_evidencia: boolean }>; estrategias_comerciais: string[] };
export type ProductRecord = { id: string; ean: string; name: string; activeIngredient: string; composition: string; laboratory: string; anvisaRegistration: string | null; currentCost: Numeric; salePrice: Numeric; stockQuantity: Numeric; minimumStock: Numeric; dailySalesAverage: Numeric; active: boolean; salesStrategy: string; promotionPrice: Numeric | null; strategyStartsAt: string | null; strategyEndsAt: string | null; strategyReason: string | null; controlLevel: string; requiresBuyerId: boolean; requiresPrescription: boolean; requiresPharmacist: boolean; retainsPrescription: boolean; minimumBuyerAge: number | null; controlRuleVersion: string | null; controlLegalBasis: string | null; category: FiscalCategory; lots: Array<{ id: string; code: string; quantity: Numeric; unitCost: Numeric; manufacturedAt: string; expiresAt: string }> };

export async function registrationApi(path: string, init?: RequestInit) {
  const response = await fetch(`/api/portal/registrations/${path}`, { ...init, headers: { ...(init?.body ? { "content-type": "application/json" } : {}), ...(init?.headers ?? {}) } });
  const payload = await response.json().catch(() => ({})) as { erro?: string; message?: string; detalhes?: unknown };
  if (!response.ok) throw new Error(payload.message ?? payload.erro ?? "Não foi possível salvar o cadastro.");
  return payload;
}
