"use client";

import { useMemo, useState } from "react";
import { currency, date, number, percent } from "../report-ui";

type Option = { id: string; name: string; code?: string; ean?: string; categoryId?: string; role?: string };
export type ManagementOptions = { stores: Array<Option & { pointsOfSale: Option[] }>; categories: Option[]; products: Option[]; sellers: Option[] };
type Abc = { id: string | null; ean: string; name: string; quantity: number; revenue: number; profit: number; share: number; cumulativeShare: number; class: "A" | "B" | "C" };
type Seller = { id: string | null; name: string; sales: number; revenue: number; discount: number; profit: number };
type Payment = { method: string; received: number; refunded: number; net: number };
type Loss = { id: string; occurredAt: string; quantity: number; amount: number; store: { name: string } | null; product: { name: string; ean: string }; lot: { code: string } | null };
type Sale = { id: string; soldAt: string; sellerName: string; store: { name: string } | null; pointOfSale: { name: string } | null; gross: number; discount: number; tax: number; profit: number; items: number };
type SaleDetail = { id: string; soldAt: string; grossAmount: string; discountAmount: string; taxAmount: string; netProfit: string; sellerName: string | null; seller: { name: string } | null; customer: { name: string | null; taxId: string } | null; cashSession: { store: { name: string }; pointOfSale: { name: string } }; payments: Array<{ id: string; method: string; amount: string; status: string }>; items: Array<{ id: string; productName: string; ean: string; ncm: string; quantity: string; unitPrice: string; unitCost: string; taxAmount: string; profitAmount: string; cfop: string; cstIcms: string; cstPis: string; cstCofins: string; cstIbsCbs: string; taxClassification: string; ruleVersion: string; taxAssessments: Array<{ id: string; status: string; ruleVersion: string; decisionHash: string; outputCfop: string; outputCstIcms: string; outputCstPisCofins: string; outputCstIbsCbs: string; outputCClassTrib: string; lot: { code: string; expiresAt: string } | null; provenance: { sourceAccessKey: string; sourceItemNumber: number } | null }> }> };
export type ManagerialReport = { company: { tradeName: string; taxRegime: string }; indicators: { sales: number; averageTicket: number; controlledItems: number; discountRate: number; lossAmount: number }; dre: { grossSales: number; discounts: number; returns: number; taxes: number; costOfGoods: number; losses: number; netRevenue: number; contribution: number; result: number; margin: number }; abc: Abc[]; sellers: Seller[]; payments: Payment[]; losses: Loss[]; sales: Sale[]; closing: { warnings: string[]; closed: { id: string; hash: string; closedAt: string; closedBy: string; note: string } | null } };

const methodLabel: Record<string, string> = { CASH: "Dinheiro", PIX: "Pix", CREDIT_CARD: "Crédito", DEBIT_CARD: "Débito", VOUCHER: "Vale", OTHER: "Outros" };

export function ManagementCenter({ initial, options, role, initialPeriod }: { initial: ManagerialReport | null; options: ManagementOptions; role: string; initialPeriod: { start: string; end: string } }) {
  const [report, setReport] = useState(initial);
  const [filters, setFilters] = useState({ start: initialPeriod.start, end: initialPeriod.end, storeId: "", pointOfSaleId: "", categoryId: "", productId: "", sellerId: "" });
  const [tab, setTab] = useState<"DRE" | "ABC" | "TEAM" | "CASH" | "SALES">("DRE");
  const [note, setNote] = useState("");
  const [busy, setBusy] = useState("");
  const [feedback, setFeedback] = useState<{ tone: "success" | "error"; text: string } | null>(null);
  const [saleDetail, setSaleDetail] = useState<SaleDetail | null>(null);
  const selectedStore = options.stores.find((item) => item.id === filters.storeId);
  const canClose = ["OWNER", "ADMIN", "MANAGER"].includes(role);
  const isFullMonth = useMemo(() => { const start = new Date(`${filters.start}T00:00:00`); const end = new Date(`${filters.end}T00:00:00`); return start.getDate() === 1 && end.getDate() === new Date(end.getFullYear(), end.getMonth() + 1, 0).getDate() && start.getMonth() === end.getMonth() && start.getFullYear() === end.getFullYear(); }, [filters.start, filters.end]);
  const payload = () => ({ inicio: filters.start, fim: filters.end, ...(filters.storeId && { loja_id: filters.storeId }), ...(filters.pointOfSaleId && { pdv_id: filters.pointOfSaleId }), ...(filters.categoryId && { categoria_id: filters.categoryId }), ...(filters.productId && { produto_id: filters.productId }), ...(filters.sellerId && { vendedor_id: filters.sellerId }) });
  const query = () => new URLSearchParams(Object.entries(payload()).map(([key, value]) => [key, String(value)])).toString();

  async function load() {
    setBusy("load"); setFeedback(null);
    try { const response = await fetch(`/api/portal/reports/gerencial?${query()}`, { cache: "no-store" }); const body = await response.json() as ManagerialReport & { message?: string }; if (!response.ok) throw new Error(body.message ?? "Não foi possível carregar o relatório."); setReport(body); }
    catch (cause) { setFeedback({ tone: "error", text: cause instanceof Error ? cause.message : "Falha ao carregar." }); } finally { setBusy(""); }
  }
  async function exportReport(format: "CSV" | "XLSX" | "PDF") {
    setBusy("export"); setFeedback(null);
    try { const response = await fetch("/api/portal/reports/gerencial/exportar", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...payload(), formato: format }) }); if (!response.ok) { const body = await response.json() as { message?: string }; throw new Error(body.message ?? "Não foi possível exportar."); } const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `nexus-gerencial-${filters.start}-${filters.end}.${format.toLowerCase()}`; anchor.click(); URL.revokeObjectURL(url); setFeedback({ tone: "success", text: `${format} gerado e exportação registrada na auditoria.` }); }
    catch (cause) { setFeedback({ tone: "error", text: cause instanceof Error ? cause.message : "Falha ao exportar." }); } finally { setBusy(""); }
  }
  async function openSale(id: string) {
    setBusy("detail"); setFeedback(null);
    try { const response = await fetch(`/api/portal/reports/gerencial/vendas/${id}`, { cache: "no-store" }); const body = await response.json() as SaleDetail & { message?: string }; if (!response.ok) throw new Error(body.message ?? "Não foi possível abrir a venda."); setSaleDetail(body); }
    catch (cause) { setFeedback({ tone: "error", text: cause instanceof Error ? cause.message : "Falha no detalhamento." }); } finally { setBusy(""); }
  }
  async function closePeriod() {
    setBusy("close"); setFeedback(null);
    try { const response = await fetch("/api/portal/reports/gerencial/fechar", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ competencia: filters.start.slice(0, 7), observacao: note }) }); const body = await response.json() as { message?: string }; if (!response.ok) throw new Error(body.message ?? "Não foi possível fechar a competência."); await load(); setFeedback({ tone: "success", text: "Competência fechada com snapshot imutável e hash de auditoria." }); }
    catch (cause) { setFeedback({ tone: "error", text: cause instanceof Error ? cause.message : "Falha no fechamento." }); } finally { setBusy(""); }
  }

  return <div className="management-center">
    <article className="report-panel management-filters">
      <label>Início<input type="date" value={filters.start} onChange={(event) => setFilters((current) => ({ ...current, start: event.target.value }))}/></label><label>Fim<input type="date" value={filters.end} onChange={(event) => setFilters((current) => ({ ...current, end: event.target.value }))}/></label>
      <label>Loja<select value={filters.storeId} onChange={(event) => setFilters((current) => ({ ...current, storeId: event.target.value, pointOfSaleId: "" }))}><option value="">Todas</option>{options.stores.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>PDV<select value={filters.pointOfSaleId} onChange={(event) => setFilters((current) => ({ ...current, pointOfSaleId: event.target.value }))}><option value="">Todos</option>{(selectedStore?.pointsOfSale ?? options.stores.flatMap((item) => item.pointsOfSale)).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label>Categoria<select value={filters.categoryId} onChange={(event) => setFilters((current) => ({ ...current, categoryId: event.target.value, productId: "" }))}><option value="">Todas</option>{options.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Produto<select value={filters.productId} onChange={(event) => setFilters((current) => ({ ...current, productId: event.target.value }))}><option value="">Todos</option>{options.products.filter((item) => !filters.categoryId || item.categoryId === filters.categoryId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Vendedor<select value={filters.sellerId} onChange={(event) => setFilters((current) => ({ ...current, sellerId: event.target.value }))}><option value="">Todos</option>{options.sellers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <div><button disabled={busy !== ""} onClick={load}>{busy === "load" ? "Atualizando…" : "Aplicar filtros"}</button><button className="secondary" disabled={busy !== "" || !report} onClick={() => exportReport("CSV")}>CSV</button><button className="secondary" disabled={busy !== "" || !report} onClick={() => exportReport("XLSX")}>XLSX</button><button className="secondary" disabled={busy !== "" || !report} onClick={() => exportReport("PDF")}>PDF</button></div>
    </article>
    {feedback && <div className={`management-feedback ${feedback.tone}`}>{feedback.text}</div>}
    {!report ? <div className="report-empty"><strong>Relatório aguardando dados</strong><p>Registre vendas para iniciar a leitura gerencial.</p></div> : <>
      <div className="report-metrics"><article className="report-metric"><span>Receita líquida</span><strong>{currency(report.dre.netRevenue)}</strong><small>{report.indicators.sales} vendas · ticket {currency(report.indicators.averageTicket)}</small></article><article className="report-metric success"><span>Resultado gerencial</span><strong>{currency(report.dre.result)}</strong><small>Margem de {percent(report.dre.margin)}</small></article><article className="report-metric"><span>Descontos</span><strong>{currency(report.dre.discounts)}</strong><small>{percent(report.indicators.discountRate)} da venda bruta</small></article><article className={`report-metric ${report.dre.losses ? "warning" : ""}`}><span>Perdas</span><strong>{currency(report.dre.losses)}</strong><small>{report.indicators.controlledItems} itens controlados vendidos</small></article></div>
      <div className="management-tabs">{([['DRE','DRE gerencial'],['ABC','Curva ABC'],['TEAM','Vendedores'],['CASH','Recebimentos'],['SALES','Vendas']] as const).map(([value,label]) => <button className={tab === value ? "active" : ""} key={value} onClick={() => setTab(value)}>{label}</button>)}</div>
      {tab === "DRE" && <div className="management-grid"><article className="report-panel management-dre"><div className="panel-title"><div><span>DEMONSTRAÇÃO INTERNA</span><h2>DRE gerencial</h2></div><strong>{filters.start} → {filters.end}</strong></div>{[["Venda bruta",report.dre.grossSales,""],["(−) Descontos",report.dre.discounts,"deduction"],["(−) Devoluções",report.dre.returns,"deduction"],["Receita líquida",report.dre.netRevenue,"total"],["(−) Tributos",report.dre.taxes,"deduction"],["(−) Custo da mercadoria",report.dre.costOfGoods,"deduction"],["Margem de contribuição",report.dre.contribution,"total"],["(−) Perdas e avarias",report.dre.losses,"deduction"],["Resultado gerencial",report.dre.result,"result"]].map(([label,value,tone]) => <div className={String(tone)} key={String(label)}><span>{label}</span><b>{currency(Number(value))}</b></div>)}<p>Relatório operacional. Não substitui contabilidade, SPED ou apuração fiscal oficial.</p></article><article className="report-panel management-closing"><div className="panel-title"><div><span>COMPETÊNCIA</span><h2>Fechamento interno</h2></div></div>{report.closing.closed ? <div className="closed-period"><span>✓</span><strong>Competência fechada</strong><p>Por {report.closing.closed.closedBy} em {date(report.closing.closed.closedAt)}</p><code>{report.closing.closed.hash}</code></div> : <><div className="closing-checks">{report.closing.warnings.length ? report.closing.warnings.map((item) => <p key={item}><span>!</span>{item}</p>) : <p className="ready"><span>✓</span>Nenhuma pendência operacional</p>}</div><textarea placeholder="Observação e responsabilidade pelo fechamento" value={note} onChange={(event) => setNote(event.target.value)}/><button disabled={!canClose || !isFullMonth || note.trim().length < 10 || report.closing.warnings.length > 0 || busy !== ""} onClick={closePeriod}>Fechar competência</button>{!isFullMonth && <small>Selecione o primeiro e o último dia do mesmo mês para fechar.</small>}</>}</article></div>}
      {tab === "ABC" && <article className="report-panel management-table"><div className="panel-title"><div><span>CONCENTRAÇÃO DE RECEITA</span><h2>Curva ABC por produto</h2></div></div><div className="management-row abc-row head"><span>Classe</span><span>Produto</span><span>Quantidade</span><span>Receita</span><span>Participação</span><span>Lucro</span></div>{report.abc.map((item) => <div className="management-row abc-row" key={item.ean}><b className={`abc abc-${item.class}`}>{item.class}</b><p><strong>{item.name}</strong><small>{item.ean}</small></p><span>{number(item.quantity, 3)}</span><span>{currency(item.revenue)}</span><span>{percent(item.share)}</span><b>{currency(item.profit)}</b></div>)}</article>}
      {tab === "TEAM" && <article className="report-panel management-table"><div className="panel-title"><div><span>PRODUTIVIDADE</span><h2>Resultado por vendedor</h2></div></div><div className="management-row seller-row head"><span>Vendedor</span><span>Vendas</span><span>Receita</span><span>Descontos</span><span>Lucro</span></div>{report.sellers.map((item) => <div className="management-row seller-row" key={item.id ?? item.name}><strong>{item.name}</strong><span>{item.sales}</span><span>{currency(item.revenue)}</span><span>{currency(item.discount)}</span><b>{currency(item.profit)}</b></div>)}</article>}
      {tab === "CASH" && <div className="management-grid"><article className="report-panel management-payments"><div className="panel-title"><div><span>FLUXO REGISTRADO</span><h2>Recebimentos por meio</h2></div></div>{report.payments.map((item) => <div key={item.method}><strong>{methodLabel[item.method] ?? item.method}</strong><span>Recebido {currency(item.received)}</span><span>Estornado {currency(item.refunded)}</span><b>{currency(item.net)}</b></div>)}</article><article className="report-panel management-losses"><div className="panel-title"><div><span>RASTREABILIDADE</span><h2>Perdas aprovadas</h2></div></div>{report.losses.length ? report.losses.map((item) => <div key={item.id}><p><strong>{item.product.name}</strong><small>{item.store?.name ?? "Sem loja"} · lote {item.lot?.code ?? "—"}</small></p><span>{number(Math.abs(item.quantity), 3)}</span><b>{currency(item.amount)}</b></div>) : <p className="management-empty">Nenhuma perda aprovada no período.</p>}</article></div>}
      {tab === "SALES" && <article className="report-panel management-table"><div className="panel-title"><div><span>DRILL-DOWN OPERACIONAL</span><h2>Vendas do período</h2></div><strong>{report.sales.length} registros</strong></div><div className="management-row sales-row head"><span>Data</span><span>Loja / PDV</span><span>Vendedor</span><span>Valor</span><span>Tributos</span><span>Lucro</span></div>{report.sales.map((item) => <button className="management-row sales-row management-drill-row" key={item.id} onClick={() => openSale(item.id)} type="button"><span>{date(item.soldAt)}</span><p><strong>{item.store?.name ?? "Sem loja"}</strong><small>{item.pointOfSale?.name ?? "Sem PDV"} · {item.items} itens</small></p><span>{item.sellerName}</span><span>{currency(item.gross)}</span><span>{currency(item.tax)}</span><b>{currency(item.profit)}</b></button>)}</article>}
    </>}
    {saleDetail && <div className="return-modal-backdrop" role="presentation"><section aria-modal="true" className="return-modal managerial-detail-modal" role="dialog"><header><div><span>VENDA · PRODUTO · LOTE · REGRA FISCAL</span><h2>{date(saleDetail.soldAt)}</h2><p>{saleDetail.cashSession.store.name} · {saleDetail.cashSession.pointOfSale.name} · {saleDetail.sellerName ?? saleDetail.seller?.name ?? "Venda legada"}</p></div><button aria-label="Fechar detalhes" onClick={() => setSaleDetail(null)} type="button">×</button></header><div className="management-metrics"><article><span>Venda</span><strong>{currency(Number(saleDetail.grossAmount))}</strong></article><article><span>Tributos</span><strong>{currency(Number(saleDetail.taxAmount))}</strong></article><article><span>Lucro</span><strong>{currency(Number(saleDetail.netProfit))}</strong></article></div><div className="managerial-detail-items">{saleDetail.items.map((item) => <article key={item.id}><header><div><strong>{item.productName}</strong><small>GTIN {item.ean} · NCM {item.ncm} · {number(Number(item.quantity), 3)} un.</small></div><b>{currency(Number(item.unitPrice) * Number(item.quantity))}</b></header><dl><div><dt>ICMS</dt><dd>CFOP {item.cfop} · CST {item.cstIcms}</dd></div><div><dt>PIS/COFINS</dt><dd>{item.cstPis}/{item.cstCofins}</dd></div><div><dt>IBS/CBS</dt><dd>{item.cstIbsCbs} · {item.taxClassification}</dd></div><div><dt>Regra aplicada</dt><dd>{item.ruleVersion}</dd></div></dl>{item.taxAssessments.map((assessment) => <div className="managerial-fiscal-trace" key={assessment.id}><strong>Lote {assessment.lot?.code ?? "não identificado"}</strong><span>Saída {assessment.outputCfop} · ICMS {assessment.outputCstIcms} · PIS/COFINS {assessment.outputCstPisCofins} · IBS/CBS {assessment.outputCstIbsCbs} · cClassTrib {assessment.outputCClassTrib}</span><small>Regra {assessment.ruleVersion} · decisão {assessment.decisionHash.slice(0, 12)}…{assessment.provenance ? ` · origem NF-e final ${assessment.provenance.sourceAccessKey.slice(-8)}` : ""}</small></div>)}</article>)}</div></section></div>}
  </div>;
}
