"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Amount = number | string;
type Opportunity = {
  id: string; type: "OUT_OF_STOCK" | "LOW_COVERAGE" | "EXPIRING" | "HIGH_DEMAND"; status: string; priority: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
  currentStock: Amount; minimumStock: Amount; expiringQuantity: Amount; salesLast30Days: Amount; salesPrevious30Days: Amount; coverageDays: Amount | null; suggestedQuantity: Amount; logisticsWindowDays: number; dueAt: string; outcome: string | null;
  assignedTo: { id: string; name: string } | null; company: { id: string; tradeName: string; city: string | null; state: string | null }; store: { id: string; name: string }; product: { id: string; name: string; ean: string; laboratory: string };
  snapshot: { salesGrowthPercent?: number; nearestExpiryAt?: string | null };
};
type Preferences = { logisticsWindowDays: number; targetCoverageDays: number; lowCoverageDays: number; expiryWindowDays: number; highDemandGrowthPercent: number; alertOutOfStock: boolean; alertLowCoverage: boolean; alertExpiring: boolean; alertHighDemand: boolean; allowedStates: string[] };
export type PrimeDashboardData = {
  generatedAt: string; organization: { id: string; code: string; tradeName: string; kind: string }; preferences: Preferences;
  indicators: { opportunities: number; critical: number; clients: number; suggestedUnits: Amount; expiringUnits: Amount; contacted: number };
  regions: Array<{ state: string; city: string; opportunities: number; clients: number; suggestedUnits: Amount }>;
  opportunities: Opportunity[];
};

const number = (value: Amount | null) => Number(value ?? 0);
const qty = (value: Amount | null) => new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 1 }).format(number(value));
const date = (value?: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(new Date(value)) : "—";
const typeLabels = { OUT_OF_STOCK: "Ruptura", LOW_COVERAGE: "Baixa cobertura", EXPIRING: "Vencimento", HIGH_DEMAND: "Alta demanda" };
const typeIcons = { OUT_OF_STOCK: "!", LOW_COVERAGE: "↓", EXPIRING: "◷", HIGH_DEMAND: "↗" };
const statusLabels: Record<string, string> = { NEW: "Nova", ASSIGNED: "Assumida", CONTACTED: "Contato feito", PROPOSAL_SENT: "Proposta enviada", WON: "Convertida", DECLINED: "Recusada", DISMISSED: "Dispensada", RESOLVED: "Normalizada" };
const ufs = ["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"];

export function PrimeDashboard({ initial }: { initial: PrimeDashboardData }) {
  const router = useRouter();
  const [query, setQuery] = useState(""); const [state, setState] = useState(""); const [type, setType] = useState("");
  const [settings, setSettings] = useState(initial.preferences); const [showSettings, setShowSettings] = useState(false);
  const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  const opportunities = useMemo(() => initial.opportunities.filter((item) => (!state || item.company.state === state) && (!type || item.type === type) && (!query || `${item.product.name} ${item.product.laboratory} ${item.company.tradeName} ${item.company.city}`.toLowerCase().includes(query.toLowerCase()))), [initial.opportunities, query, state, type]);
  const maxRegion = Math.max(...initial.regions.map((item) => item.opportunities), 1);

  async function synchronize() { setBusy("sync"); setMessage(""); const response = await fetch("/api/prime/sincronizar", { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); setBusy(""); setMessage(response.ok ? "Radar atualizado com os dados mais recentes da rede." : ((await response.json().catch(() => ({}))) as { message?: string }).message ?? "Não foi possível atualizar o radar."); if (response.ok) router.refresh(); }
  async function saveSettings() { setBusy("settings"); setMessage(""); const response = await fetch("/api/prime/configuracoes", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(settings) }); setBusy(""); setMessage(response.ok ? "Preferências logísticas atualizadas." : ((await response.json().catch(() => ({}))) as { message?: string }).message ?? "Não foi possível salvar as configurações."); if (response.ok) { setShowSettings(false); router.refresh(); } }
  async function updateOpportunity(id: string, status: string) { setBusy(id); setMessage(""); const response = await fetch(`/api/prime/oportunidades/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); setBusy(""); setMessage(response.ok ? `Oportunidade marcada como ${statusLabels[status].toLowerCase()}.` : ((await response.json().catch(() => ({}))) as { message?: string }).message ?? "Não foi possível atualizar a oportunidade."); if (response.ok) router.refresh(); }

  return <div className="prime-dashboard">
    <section className="prime-hero"><div><span>PAINEL PRIME · {initial.organization.tradeName.toUpperCase()}</span><h1>Radar de abastecimento</h1><p>Veja antes. Prepare em {settings.logisticsWindowDays} dias. Entregue antes da concorrência.</p></div><div className="prime-hero-actions"><button className="ghost" onClick={() => setShowSettings((value) => !value)} type="button">⚙ Preferências</button><button className="primary" disabled={busy === "sync"} onClick={synchronize} type="button">{busy === "sync" ? "Atualizando…" : "↻ Atualizar radar"}</button></div></section>
    {message && <div className="prime-message">{message}</div>}
    <section className="prime-kpis"><article className="urgent"><span>OPORTUNIDADES AGORA</span><strong>{initial.indicators.opportunities}</strong><small><b>{initial.indicators.critical}</b> exigem preparação imediata</small></article><article><span>CLIENTES MAPEADOS</span><strong>{initial.indicators.clients}</strong><small>em {initial.regions.length} praças ativas</small></article><article><span>REPOSIÇÃO SUGERIDA</span><strong>{qty(initial.indicators.suggestedUnits)}</strong><small>unidades para recompor cobertura</small></article><article><span>PRÓXIMOS DO VENCIMENTO</span><strong>{qty(initial.indicators.expiringUnits)}</strong><small>unidades em janela monitorada</small></article><article><span>CONTATOS EM CURSO</span><strong>{initial.indicators.contacted}</strong><small>oportunidades já trabalhadas</small></article></section>
    {showSettings && <section className="prime-settings" id="configuracoes"><div className="prime-section-title"><div><span>CONFIGURAÇÃO OPERACIONAL</span><h2>Ajuste o radar à sua logística</h2><p>Escolha o que deve gerar alerta e em quantos dias sua equipe consegue preparar a entrega.</p></div><button onClick={() => setShowSettings(false)} type="button">×</button></div><div className="prime-settings-grid"><label>Janela logística<select value={settings.logisticsWindowDays} onChange={(event) => setSettings({ ...settings, logisticsWindowDays: Number(event.target.value) })}>{[2,3,4,5].map((day) => <option key={day} value={day}>{day} dias</option>)}</select><small>Prazo esperado para separar e disponibilizar.</small></label><label>Cobertura desejada<input min={7} max={90} type="number" value={settings.targetCoverageDays} onChange={(event) => setSettings({ ...settings, targetCoverageDays: Number(event.target.value) })}/><small>Dias usados na sugestão de reposição.</small></label><label>Alerta de baixa cobertura<input min={1} max={45} type="number" value={settings.lowCoverageDays} onChange={(event) => setSettings({ ...settings, lowCoverageDays: Number(event.target.value) })}/><small>Dispara abaixo deste número de dias.</small></label><label>Janela de vencimento<select value={settings.expiryWindowDays} onChange={(event) => setSettings({ ...settings, expiryWindowDays: Number(event.target.value) })}>{[30,60,90,120,180].map((day) => <option key={day} value={day}>{day} dias</option>)}</select><small>Quantidade que pode perder capacidade de venda.</small></label></div><div className="prime-alert-toggles"><Toggle checked={settings.alertOutOfStock} label="Ruptura" onChange={(checked) => setSettings({ ...settings, alertOutOfStock: checked })}/><Toggle checked={settings.alertLowCoverage} label="Baixa cobertura" onChange={(checked) => setSettings({ ...settings, alertLowCoverage: checked })}/><Toggle checked={settings.alertExpiring} label="Vencimento" onChange={(checked) => setSettings({ ...settings, alertExpiring: checked })}/><Toggle checked={settings.alertHighDemand} label="Alta demanda" onChange={(checked) => setSettings({ ...settings, alertHighDemand: checked })}/></div><button className="primary save-prime-settings" disabled={busy === "settings"} onClick={saveSettings} type="button">{busy === "settings" ? "Salvando…" : "Salvar padrão do radar"}</button></section>}
    <section className="prime-main-grid"><article className="prime-regions" id="regioes"><div className="prime-section-title"><div><span>CALOR REGIONAL</span><h2>Onde a demanda está se formando</h2></div><strong>{initial.regions.length}</strong></div><div className="prime-region-list">{initial.regions.slice(0,8).map((region) => <button key={`${region.state}-${region.city}`} onClick={() => { setState(region.state); setQuery(region.city === "Não informado" ? "" : region.city); }} type="button"><div><b>{region.city}</b><span>{region.state} · {region.clients} cliente(s)</span></div><div className="region-bar"><i style={{ width: `${Math.max(8, region.opportunities / maxRegion * 100)}%` }}/></div><strong>{region.opportunities}<small>alertas</small></strong></button>)}</div></article><article className="prime-logistics"><div className="prime-section-title"><div><span>JANELA DE VANTAGEM</span><h2>Preparação em 2–5 dias</h2></div><span className="prime-day-pill">{settings.logisticsWindowDays} dias</span></div><div className="logistics-track"><div className="active"><span>Hoje</span><strong>Radar detecta</strong><small>ruptura, giro e validade</small></div><div><span>D+1</span><strong>Time prioriza</strong><small>cliente, região e produto</small></div><div><span>D+{settings.logisticsWindowDays}</span><strong>Entrega preparada</strong><small>atendimento antes da falta</small></div></div><div className="prime-logistics-callout"><span>↗</span><div><strong>Vantagem Prime</strong><p>O contato chega quando a necessidade está se formando, não depois que o cliente já ficou sem o produto.</p></div></div></article></section>
    <section className="prime-opportunities" id="oportunidades"><div className="prime-section-title opportunity-title"><div><span>FILA COMERCIAL INTELIGENTE</span><h2>Oportunidades por cliente e produto</h2><p>Todos os produtos entram no radar, mesmo fora do catálogo atual do fornecedor.</p></div><strong>{opportunities.length}</strong></div><div className="prime-filters"><label><span>⌕</span><input aria-label="Buscar oportunidade" placeholder="Produto, laboratório, cliente ou cidade" value={query} onChange={(event) => setQuery(event.target.value)}/></label><select aria-label="Filtrar estado" value={state} onChange={(event) => setState(event.target.value)}><option value="">Todos os estados</option>{ufs.map((uf) => <option key={uf}>{uf}</option>)}</select><select aria-label="Filtrar alerta" value={type} onChange={(event) => setType(event.target.value)}><option value="">Todos os alertas</option>{Object.entries(typeLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select>{(query || state || type) && <button onClick={() => { setQuery(""); setState(""); setType(""); }} type="button">Limpar</button>}</div><div className="prime-opportunity-table"><div className="prime-table-head"><span>Prioridade e cliente</span><span>Produto</span><span>Sinal operacional</span><span>Preparação</span><span>Ação</span></div>{opportunities.length ? opportunities.map((item) => <OpportunityRow busy={busy === item.id} item={item} key={item.id} onUpdate={updateOpportunity}/>) : <div className="prime-empty"><strong>Nenhuma oportunidade neste recorte.</strong><p>Altere os filtros ou atualize o radar.</p></div>}</div></section>
  </div>;
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="prime-toggle"><input checked={checked} onChange={(event) => onChange(event.target.checked)} type="checkbox"/><i/><span>{label}</span></label>; }

function OpportunityRow({ item, busy, onUpdate }: { item: Opportunity; busy: boolean; onUpdate: (id: string, status: string) => void }) {
  const growth = item.snapshot?.salesGrowthPercent ?? (number(item.salesPrevious30Days) ? ((number(item.salesLast30Days) - number(item.salesPrevious30Days)) / number(item.salesPrevious30Days)) * 100 : 0);
  return <article className={`prime-opportunity-row priority-${item.priority.toLowerCase()}`}><div className="prime-client-cell"><span className={`prime-signal-icon signal-${item.type.toLowerCase()}`}>{typeIcons[item.type]}</span><div><strong>{item.company.tradeName}</strong><small>{item.company.city ?? "Local não informado"}/{item.company.state ?? "--"} · {item.store.name}</small><em>{item.priority === "CRITICAL" ? "Prioridade imediata" : item.priority === "HIGH" ? "Alta prioridade" : "Monitorar"}</em></div></div><div className="prime-product-cell"><strong>{item.product.name}</strong><small>{item.product.laboratory || "Laboratório não informado"} · EAN {item.product.ean}</small><span>{typeLabels[item.type]}</span></div><div className="prime-signal-data"><div><span>Saldo</span><b>{qty(item.currentStock)}</b></div><div><span>Vendas 30d</span><b>{qty(item.salesLast30Days)}</b></div><div><span>A vencer</span><b>{qty(item.expiringQuantity)}</b></div>{item.type === "HIGH_DEMAND" && <em>↗ {growth.toFixed(0)}%</em>}</div><div className="prime-preparation"><span>Reposição sugerida</span><strong>{qty(item.suggestedQuantity)} <small>un.</small></strong><em>Preparar até {date(item.dueAt)}</em>{item.coverageDays !== null && <small>{qty(item.coverageDays)} dias de cobertura</small>}</div><div className="prime-row-action"><span>{statusLabels[item.status] ?? item.status}</span><select aria-label={`Ação para ${item.product.name}`} disabled={busy} onChange={(event) => event.target.value && onUpdate(item.id, event.target.value)} value=""><option value="">Registrar ação</option><option value="ASSIGNED">Assumir oportunidade</option><option value="CONTACTED">Contato realizado</option><option value="PROPOSAL_SENT">Proposta enviada</option><option value="WON">Venda convertida</option><option value="DECLINED">Cliente recusou</option><option value="DISMISSED">Dispensar alerta</option></select></div></article>;
}
