"use client";

import { useEffect, useMemo, useState } from "react";
import { getOfflineSnapshot, pendingOfflineCount, queueOfflineSale, type OfflineSnapshotPayload, unlockOffline } from "../portal/caixa/offline-store";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
export function OfflineCashApp() {
  const [pin, setPin] = useState(""); const [snapshot, setSnapshot] = useState<OfflineSnapshotPayload | null>(null); const [productEan, setProductEan] = useState(""); const [quantity, setQuantity] = useState("1"); const [cart, setCart] = useState<Array<{ ean: string; name: string; price: number; quantity: number }>>([]); const [pending, setPending] = useState(0); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void pendingOfflineCount().then(setPending); }, []);
  const products = useMemo(() => snapshot?.products.filter((product) => product.allowedOffline) ?? [], [snapshot]); const total = useMemo(() => Math.round(cart.reduce((sum, item) => sum + item.price * item.quantity, 0) * 100) / 100, [cart]); const expired = snapshot ? new Date(snapshot.expiresAt) <= new Date() : true;
  async function unlock() { setError(""); try { await unlockOffline(pin); const saved = await getOfflineSnapshot(); if (!saved) throw new Error("Snapshot offline não encontrado."); setSnapshot(saved.payload); setProductEan(saved.payload.products.find((product) => product.allowedOffline)?.ean ?? ""); setPin(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível abrir o caixa."); } }
  function add() { const product = products.find((entry) => entry.ean === productEan); const amount = Number(quantity); if (!product || amount <= 0) return; setCart((current) => { const found = current.find((entry) => entry.ean === product.ean); return found ? current.map((entry) => entry.ean === product.ean ? { ...entry, quantity: entry.quantity + amount } : entry) : [...current, { ean: product.ean, name: product.name, price: product.commercialPrice, quantity: amount }]; }); }
  async function finish() { if (!snapshot || !cart.length) return; setError(""); try { await queueOfflineSale({ modelo_nota: "65", sessao_caixa_id: snapshot.cashSessionId, desconto_percentual: 0, vendedor_id: snapshot.operatorId, farmaceutico_credencial_id: null, consumidor: null, itens: cart.map((item) => ({ ean: item.ean, quantidade: item.quantity, prescricao: null })), pagamentos: [{ metodo: "CASH", valor: total, referencia_externa: null }] }); setCart([]); setPending(await pendingOfflineCount()); setMessage("Venda guardada com segurança. Sincronize ao restabelecer a conexão."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Venda offline bloqueada."); } }
  if (!snapshot) return <main className="offline-cash-app locked"><section><img alt="Nexus Pharma" src="/logo/icon-nexus-pharma.png"/><span>CAIXA LOCAL PROTEGIDO</span><h1>Desbloquear operação offline</h1><p>Use o PIN configurado neste dispositivo. Nenhum dado comercial está contido nesta página.</p><input aria-label="PIN offline" autoFocus inputMode="numeric" maxLength={6} onChange={(event) => setPin(event.target.value.replace(/\D/g, ""))} placeholder="PIN de 6 números" type="password" value={pin}/><button disabled={pin.length !== 6} onClick={unlock}>Desbloquear</button>{error && <em>{error}</em>}</section></main>;
  return <main className="offline-cash-app"><header><div><span>● MODO OFFLINE</span><h1>Caixa local</h1><small>Snapshot até {new Date(snapshot.expiresAt).toLocaleString("pt-BR")}</small></div><div><small>Fila protegida</small><strong>{pending}</strong></div><a href="/portal/caixa">Voltar ao portal</a></header>{expired && <div className="offline-expired">Snapshot vencido. Reconecte o caixa antes de realizar novas vendas.</div>}<section className="offline-sale-panel"><div className="offline-product-picker"><select disabled={expired} onChange={(event) => setProductEan(event.target.value)} value={productEan}>{products.map((product) => <option key={product.ean} value={product.ean}>{product.name} · {brl.format(product.commercialPrice)} · saldo {product.available}</option>)}</select><input disabled={expired} min="0.001" onChange={(event) => setQuantity(event.target.value)} step="0.001" type="number" value={quantity}/><button disabled={expired || !productEan} onClick={add}>Adicionar</button></div><div className="offline-cart">{cart.length === 0 ? <p>Adicione os produtos da venda.</p> : cart.map((item) => <article key={item.ean}><span>{item.quantity}×</span><div><strong>{item.name}</strong><small>{item.ean}</small></div><b>{brl.format(item.price * item.quantity)}</b><button onClick={() => setCart((current) => current.filter((entry) => entry.ean !== item.ean))}>×</button></article>)}</div><footer><div><small>Recebimento</small><strong>Dinheiro</strong></div><div><small>Total</small><strong>{brl.format(total)}</strong></div><button disabled={expired || !cart.length} onClick={finish}>Concluir venda offline</button></footer>{message && <p className="ok">{message}</p>}{error && <p className="error">{error}</p>}</section><aside><strong>Restrições de segurança</strong><p>Produtos controlados, Pix, cartões, descontos manuais e regras sem vigência exigem conexão.</p></aside></main>;
}
